server:
  port: 8080

spring:
  application:
    name: recipe-platform-backend
  servlet:
    multipart:
      enabled: true
      max-request-size: 3MB
      max-file-size: 2MB

  datasource:
    url: jdbc:mysql://localhost:3306/recipe
    username: root
    password: ahmad1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    com.recipeplatform: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  jwt:
   secret: hello-this-is-my-secrect-key-for-generating-jwt-token-and-it-help-in-jwt
   expiration: 14400000

  file-upload:
    dir:  upload/images

